### ISSUE TITLE
Support cross-compiling

### ISSUE THREAD

**Issue by singpolyma** [jystic/network-info#13]
`#let` is not supported in hsc2hs when cross-compiling, neither is `#alignment`

**Comment by AlexeyRaga** [comment]
Is there any progress on this issue?
There was a workaround suggested here:
https://ghc.haskell.org/trac/ghc/ticket/10272

**Comment by jystic** [comment]
@AlexeyRaga I wasn't aware of this workaround, I'm giving it a try locally

**Comment by jystic** [comment]
@AlexeyRaga I've just pushed a fix to master, are you able to try it out and let me know if it works for your situation?

**Comment by AlexeyRaga** [comment]
ok, I'll try now

**Comment by AlexeyRaga** [comment]
It looks like it worked.
I was able to cross-compile to ARMv7 using GHC 7.10.2 cross-compiler.
Thanks for making the change really quick, waiting for a new version on hackage.

**Comment by jystic** [comment]
Excellent! I'll package it up now

**Comment by jystic** [comment]
This is fixed and available on hackage as [network-info-0.2.0.8](http://hackage.haskell.org/package/network-info-0.2.0.8)

**Comment by jystic** [comment]
@AlexeyRaga Thanks so much for pointing out the workaround!
